/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "use-controllable-state": {
    name: "use-controllable-state",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-layout-effect.tsx",
      type: "registry:hook",
    },{
      path: "src/registry/src/hooks/use-controllable-state.ts",
      type: "registry:hook",
    }],
  },
  "theme-switcher": {
    name: "theme-switcher",
    description: "A theme switcher component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "src/registry/theme-switcher/theme-switcher.tsx",
      type: "registry:component",
    }],
  },
  "flip-sentences": {
    name: "flip-sentences",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/flip-sentences/flip-sentences.tsx",
      type: "registry:component",
    }],
  },
  "apple-hello-effect": {
    name: "apple-hello-effect",
    description: "Create a Xin chào and Hello writing effect inspired by Apple using Motion for React.",
    type: "registry:component",
    files: [{
      path: "src/registry/apple-hello-effect/apple-hello-effect.tsx",
      type: "registry:component",
    }],
  },
  "wheel-picker": {
    name: "wheel-picker",
    description: "iOS-like wheel picker for React with smooth inertia scrolling and infinite loop support.",
    type: "registry:component",
    files: [{
      path: "src/registry/wheel-picker/wheel-picker.tsx",
      type: "registry:component",
    }],
  },
  "work-experience": {
    name: "work-experience",
    description: "Displays a list of work experiences with role details and durations.",
    type: "registry:component",
    files: [{
      path: "src/registry/work-experience/work-experience.tsx",
      type: "registry:component",
    }],
  },
  "glowing-orb": {
    name: "glowing-orb",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/glowing-orb/glowing-orb.tsx",
      type: "registry:component",
    }],
  },
  "morphing-text": {
    name: "morphing-text",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/morphing-text/morphing-text.tsx",
      type: "registry:component",
    }],
  },
  "spotlight-card": {
    name: "spotlight-card",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/spotlight-card/spotlight-card.tsx",
      type: "registry:component",
    }],
  },
  "neon-clock": {
    name: "neon-clock",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/neon-clock/neon-clock.tsx",
      type: "registry:component",
    }],
  },
  "apple-hello-effect-vi-demo": {
    name: "apple-hello-effect-vi-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-vi-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/apple-hello-effect-vi-demo.tsx")),
  },
  "apple-hello-effect-en-demo": {
    name: "apple-hello-effect-en-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-en-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/apple-hello-effect-en-demo.tsx")),
  },
  "theme-switcher-demo": {
    name: "theme-switcher-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-switcher-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/theme-switcher-demo.tsx")),
  },
  "wheel-picker-demo": {
    name: "wheel-picker-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-demo.tsx")),
  },
  "wheel-picker-form-demo": {
    name: "wheel-picker-form-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-form-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-form-demo.tsx")),
  },
  "work-experience-demo": {
    name: "work-experience-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/work-experience-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/work-experience-demo.tsx")),
  },
  "glowing-orb-demo": {
    name: "glowing-orb-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/glowing-orb-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/glowing-orb-demo.tsx")),
  },
  "morphing-text-demo": {
    name: "morphing-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/morphing-text-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/morphing-text-demo.tsx")),
  },
  "spotlight-card-demo": {
    name: "spotlight-card-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/spotlight-card-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/spotlight-card-demo.tsx")),
  },
  "neon-clock-demo": {
    name: "neon-clock-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/neon-clock-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/neon-clock-demo.tsx")),
  },
  "dot-grid-spotlight": {
    name: "dot-grid-spotlight",
    description: "An interactive dot-grid canvas component that highlights dots near the cursor with a customisable spotlight glow effect.",
    type: "registry:component",
    files: [{
      path: "src/registry/dot-grid-spotlight/dot-grid-spotlight.tsx",
      type: "registry:component",
    }],
  },
  "shimmering-text": {
    name: "shimmering-text",
    description: "A pure-CSS shimmer animation for text that sweeps a highlight across characters.",
    type: "registry:component",
    files: [{
      path: "src/registry/shimmering-text/shimmering-text.tsx",
      type: "registry:component",
    }],
  },
  "spinning-circular-text": {
    name: "spinning-circular-text",
    description: "Characters arranged in a circle that continuously spin.",
    type: "registry:component",
    files: [{
      path: "src/registry/spinning-circular-text/spinning-circular-text.tsx",
      type: "registry:component",
    }],
  },
  "testimonials-marquee": {
    name: "testimonials-marquee",
    description: "A continuous horizontal marquee of testimonial cards.",
    type: "registry:component",
    files: [{
      path: "src/registry/testimonials-marquee/testimonials-marquee.tsx",
      type: "registry:component",
    }],
  },
  "glow-card-grid": {
    name: "glow-card-grid",
    description: "A responsive grid of cards that emit a radial glow following the mouse cursor.",
    type: "registry:component",
    files: [{
      path: "src/registry/glow-card-grid/glow-card-grid.tsx",
      type: "registry:component",
    }],
  },
  "elastic-slider": {
    name: "elastic-slider",
    description: "A smooth, elastic-feeling range slider with floating value label and custom accent color.",
    type: "registry:component",
    files: [{
      path: "src/registry/elastic-slider/elastic-slider.tsx",
      type: "registry:component",
    }],
  },
  "dot-grid-spotlight-demo": {
    name: "dot-grid-spotlight-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/dot-grid-spotlight-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/dot-grid-spotlight-demo.tsx")),
  },
  "shimmering-text-demo": {
    name: "shimmering-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmering-text-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/shimmering-text-demo.tsx")),
  },
  "spinning-circular-text-demo": {
    name: "spinning-circular-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/spinning-circular-text-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/spinning-circular-text-demo.tsx")),
  },
  "testimonials-marquee-demo": {
    name: "testimonials-marquee-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonials-marquee-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/testimonials-marquee-demo.tsx")),
  },
  "glow-card-grid-demo": {
    name: "glow-card-grid-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/glow-card-grid-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/glow-card-grid-demo.tsx")),
  },
  "elastic-slider-demo": {
    name: "elastic-slider-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/elastic-slider-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/elastic-slider-demo.tsx")),
  },
  "slide-to-unlock": { name: "slide-to-unlock", type: "registry:component", files: [{ path: "src/registry/slide-to-unlock/slide-to-unlock.tsx", type: "registry:component" }] },
  "slide-to-unlock-demo": { name: "slide-to-unlock-demo", type: "registry:example", files: [{ path: "src/registry/examples/slide-to-unlock-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/slide-to-unlock-demo.tsx")) },
  "copy-button": { name: "copy-button", type: "registry:component", files: [{ path: "src/registry/copy-button/copy-button.tsx", type: "registry:component" }] },
  "copy-button-demo": { name: "copy-button-demo", type: "registry:example", files: [{ path: "src/registry/examples/copy-button-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/copy-button-demo.tsx")) },
  "fluid-gradient-text": { name: "fluid-gradient-text", type: "registry:component", files: [{ path: "src/registry/fluid-gradient-text/fluid-gradient-text.tsx", type: "registry:component" }] },
  "fluid-gradient-text-demo": { name: "fluid-gradient-text-demo", type: "registry:example", files: [{ path: "src/registry/examples/fluid-gradient-text-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/fluid-gradient-text-demo.tsx")) },
  "scroll-fade-effect": { name: "scroll-fade-effect", type: "registry:component", files: [{ path: "src/registry/scroll-fade-effect/scroll-fade-effect.tsx", type: "registry:component" }] },
  "scroll-fade-effect-demo": { name: "scroll-fade-effect-demo", type: "registry:example", files: [{ path: "src/registry/examples/scroll-fade-effect-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/scroll-fade-effect-demo.tsx")) },
  "text-flip": { name: "text-flip", type: "registry:component", files: [{ path: "src/registry/text-flip/text-flip.tsx", type: "registry:component" }] },
  "text-flip-demo": { name: "text-flip-demo", type: "registry:example", files: [{ path: "src/registry/examples/text-flip-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/text-flip-demo.tsx")) },
  "testimonial": { name: "testimonial", type: "registry:component", files: [{ path: "src/registry/testimonial/testimonial.tsx", type: "registry:component" }] },
  "testimonial-demo": { name: "testimonial-demo", type: "registry:example", files: [{ path: "src/registry/examples/testimonial-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/testimonial-demo.tsx")) },
  "testimonial-spotlight": { name: "testimonial-spotlight", type: "registry:component", files: [{ path: "src/registry/testimonial-spotlight/testimonial-spotlight.tsx", type: "registry:component" }] },
  "testimonial-spotlight-demo": { name: "testimonial-spotlight-demo", type: "registry:example", files: [{ path: "src/registry/examples/testimonial-spotlight-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/testimonial-spotlight-demo.tsx")) },
  "number-counter": { name: "number-counter", type: "registry:component", files: [{ path: "src/registry/number-counter/number-counter.tsx", type: "registry:component" }] },
  "number-counter-demo": { name: "number-counter-demo", type: "registry:example", files: [{ path: "src/registry/examples/number-counter-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/number-counter-demo.tsx")) },
  "progress-ring": { name: "progress-ring", type: "registry:component", files: [{ path: "src/registry/progress-ring/progress-ring.tsx", type: "registry:component" }] },
  "progress-ring-demo": { name: "progress-ring-demo", type: "registry:example", files: [{ path: "src/registry/examples/progress-ring-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/progress-ring-demo.tsx")) },
  "gradient-border-card": { name: "gradient-border-card", type: "registry:component", files: [{ path: "src/registry/gradient-border-card/gradient-border-card.tsx", type: "registry:component" }] },
  "gradient-border-card-demo": { name: "gradient-border-card-demo", type: "registry:example", files: [{ path: "src/registry/examples/gradient-border-card-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/gradient-border-card-demo.tsx")) },
  "typewriter-effect": { name: "typewriter-effect", type: "registry:component", files: [{ path: "src/registry/typewriter-effect/typewriter-effect.tsx", type: "registry:component" }] },
  "typewriter-effect-demo": { name: "typewriter-effect-demo", type: "registry:example", files: [{ path: "src/registry/examples/typewriter-effect-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/typewriter-effect-demo.tsx")) },
  "magnetic-button": { name: "magnetic-button", type: "registry:component", files: [{ path: "src/registry/magnetic-button/magnetic-button.tsx", type: "registry:component" }] },
  "magnetic-button-demo": { name: "magnetic-button-demo", type: "registry:example", files: [{ path: "src/registry/examples/magnetic-button-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/magnetic-button-demo.tsx")) },
  "avatar-group": { name: "avatar-group", type: "registry:component", files: [{ path: "src/registry/avatar-group/avatar-group.tsx", type: "registry:component" }] },
  "avatar-group-demo": { name: "avatar-group-demo", type: "registry:example", files: [{ path: "src/registry/examples/avatar-group-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/avatar-group-demo.tsx")) },
  "stat-card": { name: "stat-card", type: "registry:component", files: [{ path: "src/registry/stat-card/stat-card.tsx", type: "registry:component" }] },
  "stat-card-demo": { name: "stat-card-demo", type: "registry:example", files: [{ path: "src/registry/examples/stat-card-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/stat-card-demo.tsx")) },
  "timeline": { name: "timeline", type: "registry:component", files: [{ path: "src/registry/timeline/timeline.tsx", type: "registry:component" }] },
  "timeline-demo": { name: "timeline-demo", type: "registry:example", files: [{ path: "src/registry/examples/timeline-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/timeline-demo.tsx")) },
  "pricing-card": { name: "pricing-card", type: "registry:component", files: [{ path: "src/registry/pricing-card/pricing-card.tsx", type: "registry:component" }] },
  "pricing-card-demo": { name: "pricing-card-demo", type: "registry:example", files: [{ path: "src/registry/examples/pricing-card-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/pricing-card-demo.tsx")) },
  "step-progress": { name: "step-progress", type: "registry:component", files: [{ path: "src/registry/step-progress/step-progress.tsx", type: "registry:component" }] },
  "step-progress-demo": { name: "step-progress-demo", type: "registry:example", files: [{ path: "src/registry/examples/step-progress-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/step-progress-demo.tsx")) },
  "badge-collection": { name: "badge-collection", type: "registry:component", files: [{ path: "src/registry/badge-collection/badge-collection.tsx", type: "registry:component" }] },
  "badge-collection-demo": { name: "badge-collection-demo", type: "registry:example", files: [{ path: "src/registry/examples/badge-collection-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/badge-collection-demo.tsx")) },
  "skeleton-loader": { name: "skeleton-loader", type: "registry:component", files: [{ path: "src/registry/skeleton-loader/skeleton-loader.tsx", type: "registry:component" }] },
  "skeleton-loader-demo": { name: "skeleton-loader-demo", type: "registry:example", files: [{ path: "src/registry/examples/skeleton-loader-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/skeleton-loader-demo.tsx")) },
  "feature-card": { name: "feature-card", type: "registry:component", files: [{ path: "src/registry/feature-card/feature-card.tsx", type: "registry:component" }] },
  "feature-card-demo": { name: "feature-card-demo", type: "registry:example", files: [{ path: "src/registry/examples/feature-card-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/feature-card-demo.tsx")) },
  "code-snippet": { name: "code-snippet", type: "registry:component", files: [{ path: "src/registry/code-snippet/code-snippet.tsx", type: "registry:component" }] },
  "code-snippet-demo": { name: "code-snippet-demo", type: "registry:example", files: [{ path: "src/registry/examples/code-snippet-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/code-snippet-demo.tsx")) },
  "particle-cursor": { name: "particle-cursor", type: "registry:component", files: [{ path: "src/registry/particle-cursor/particle-cursor.tsx", type: "registry:component" }] },
  "particle-cursor-demo": { name: "particle-cursor-demo", type: "registry:example", files: [{ path: "src/registry/examples/particle-cursor-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/particle-cursor-demo.tsx")) },
  "tilt-card": { name: "tilt-card", type: "registry:component", files: [{ path: "src/registry/tilt-card/tilt-card.tsx", type: "registry:component" }] },
  "tilt-card-demo": { name: "tilt-card-demo", type: "registry:example", files: [{ path: "src/registry/examples/tilt-card-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/tilt-card-demo.tsx")) },
  "animated-tabs": { name: "animated-tabs", type: "registry:component", files: [{ path: "src/registry/animated-tabs/animated-tabs.tsx", type: "registry:component" }] },
  "animated-tabs-demo": { name: "animated-tabs-demo", type: "registry:example", files: [{ path: "src/registry/examples/animated-tabs-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/animated-tabs-demo.tsx")) },
  "accordion": { name: "accordion", type: "registry:component", files: [{ path: "src/registry/accordion/accordion.tsx", type: "registry:component" }] },
  "accordion-demo": { name: "accordion-demo", type: "registry:example", files: [{ path: "src/registry/examples/accordion-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/accordion-demo.tsx")) },
  "github-contributions": { name: "github-contributions", type: "registry:component", files: [{ path: "src/registry/github-contributions/github-contributions.tsx", type: "registry:component" }] },
  "github-contributions-demo": { name: "github-contributions-demo", type: "registry:example", files: [{ path: "src/registry/examples/github-contributions-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/github-contributions-demo.tsx")) },
  "github-stars": { name: "github-stars", type: "registry:component", files: [{ path: "src/registry/github-stars/github-stars.tsx", type: "registry:component" }] },
  "github-stars-demo": { name: "github-stars-demo", type: "registry:example", files: [{ path: "src/registry/examples/github-stars-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/github-stars-demo.tsx")) },
  "middle-truncation": { name: "middle-truncation", type: "registry:component", files: [{ path: "src/registry/middle-truncation/middle-truncation.tsx", type: "registry:component" }] },
  "middle-truncation-demo": { name: "middle-truncation-demo", type: "registry:example", files: [{ path: "src/registry/examples/middle-truncation-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/middle-truncation-demo.tsx")) },
  "theme-toggle-effect": { name: "theme-toggle-effect", type: "registry:component", files: [{ path: "src/registry/theme-toggle-effect/theme-toggle-effect.tsx", type: "registry:component" }] },
  "theme-toggle-effect-demo": { name: "theme-toggle-effect-demo", type: "registry:example", files: [{ path: "src/registry/examples/theme-toggle-effect-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/theme-toggle-effect-demo.tsx")) },
  "icon-swap": { name: "icon-swap", type: "registry:component", files: [{ path: "src/registry/icon-swap/icon-swap.tsx", type: "registry:component" }] },
  "icon-swap-demo": { name: "icon-swap-demo", type: "registry:example", files: [{ path: "src/registry/examples/icon-swap-demo.tsx", type: "registry:example" }], component: React.lazy(() => import("@/registry/examples/icon-swap-demo.tsx")) },
}