/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "use-controllable-state": {
    name: "use-controllable-state",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-layout-effect.tsx",
      type: "registry:hook",
    },{
      path: "src/registry/src/hooks/use-controllable-state.ts",
      type: "registry:hook",
    }],
  },
  "theme-switcher": {
    name: "theme-switcher",
    description: "A theme switcher component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "src/registry/theme-switcher/theme-switcher.tsx",
      type: "registry:component",
    }],
  },
  "flip-sentences": {
    name: "flip-sentences",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/flip-sentences/flip-sentences.tsx",
      type: "registry:component",
    }],
  },
  "apple-hello-effect": {
    name: "apple-hello-effect",
    description: "Create a Xin chào and Hello writing effect inspired by Apple using Motion for React.",
    type: "registry:component",
    files: [{
      path: "src/registry/apple-hello-effect/apple-hello-effect.tsx",
      type: "registry:component",
    }],
  },
  "wheel-picker": {
    name: "wheel-picker",
    description: "iOS-like wheel picker for React with smooth inertia scrolling and infinite loop support.",
    type: "registry:component",
    files: [{
      path: "src/registry/wheel-picker/wheel-picker.tsx",
      type: "registry:component",
    }],
  },
  "work-experience": {
    name: "work-experience",
    description: "Displays a list of work experiences with role details and durations.",
    type: "registry:component",
    files: [{
      path: "src/registry/work-experience/work-experience.tsx",
      type: "registry:component",
    }],
  },
  "glowing-orb": {
    name: "glowing-orb",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/glowing-orb/glowing-orb.tsx",
      type: "registry:component",
    }],
  },
  "morphing-text": {
    name: "morphing-text",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/morphing-text/morphing-text.tsx",
      type: "registry:component",
    }],
  },
  "spotlight-card": {
    name: "spotlight-card",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/spotlight-card/spotlight-card.tsx",
      type: "registry:component",
    }],
  },
  "neon-clock": {
    name: "neon-clock",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/neon-clock/neon-clock.tsx",
      type: "registry:component",
    }],
  },
  "dot-grid-spotlight": {
    name: "dot-grid-spotlight",
    description: "An interactive dot-grid canvas component that highlights dots near the cursor with a customisable spotlight glow effect.",
    type: "registry:component",
    files: [{
      path: "src/registry/dot-grid-spotlight/dot-grid-spotlight.tsx",
      type: "registry:component",
    }],
  },
  "shimmering-text": {
    name: "shimmering-text",
    description: "A pure-CSS shimmer animation for text that sweeps a highlight across characters.",
    type: "registry:component",
    files: [{
      path: "src/registry/shimmering-text/shimmering-text.tsx",
      type: "registry:component",
    }],
  },
  "spinning-circular-text": {
    name: "spinning-circular-text",
    description: "Characters arranged in a circle that continuously spin — built with SVG and CSS keyframes.",
    type: "registry:component",
    files: [{
      path: "src/registry/spinning-circular-text/spinning-circular-text.tsx",
      type: "registry:component",
    }],
  },
  "testimonials-marquee": {
    name: "testimonials-marquee",
    description: "A continuous horizontal marquee of testimonial cards with pause-on-hover, configurable speed, and fade-out edges.",
    type: "registry:component",
    files: [{
      path: "src/registry/testimonials-marquee/testimonials-marquee.tsx",
      type: "registry:component",
    }],
  },
  "glow-card-grid": {
    name: "glow-card-grid",
    description: "A responsive grid of cards that emit a radial glow following the mouse cursor.",
    type: "registry:component",
    files: [{
      path: "src/registry/glow-card-grid/glow-card-grid.tsx",
      type: "registry:component",
    }],
  },
  "elastic-slider": {
    name: "elastic-slider",
    description: "A smooth, elastic-feeling range slider with floating value label and custom accent color.",
    type: "registry:component",
    files: [{
      path: "src/registry/elastic-slider/elastic-slider.tsx",
      type: "registry:component",
    }],
  },
  "slide-to-unlock": {
    name: "slide-to-unlock",
    description: "Draggable unlock slider with elastic spring-back.",
    type: "registry:component",
    files: [{
      path: "src/registry/slide-to-unlock/slide-to-unlock.tsx",
      type: "registry:component",
    }],
  },
  "copy-button": {
    name: "copy-button",
    description: "Clipboard copy button with animated confirmation state.",
    type: "registry:component",
    files: [{
      path: "src/registry/copy-button/copy-button.tsx",
      type: "registry:component",
    }],
  },
  "fluid-gradient-text": {
    name: "fluid-gradient-text",
    description: "Text with a continuously flowing multi-color gradient animation.",
    type: "registry:component",
    files: [{
      path: "src/registry/fluid-gradient-text/fluid-gradient-text.tsx",
      type: "registry:component",
    }],
  },
  "scroll-fade-effect": {
    name: "scroll-fade-effect",
    description: "Intersection-observer reveal animation in 4 directions.",
    type: "registry:component",
    files: [{
      path: "src/registry/scroll-fade-effect/scroll-fade-effect.tsx",
      type: "registry:component",
    }],
  },
  "text-flip": {
    name: "text-flip",
    description: "Cycles through an array of words with a 3D flip transition.",
    type: "registry:component",
    files: [{
      path: "src/registry/text-flip/text-flip.tsx",
      type: "registry:component",
    }],
  },
  "testimonial": {
    name: "testimonial",
    description: "Testimonial card with card, minimal and spotlight variants.",
    type: "registry:component",
    files: [{
      path: "src/registry/testimonial/testimonial.tsx",
      type: "registry:component",
    }],
  },
  "testimonial-spotlight": {
    name: "testimonial-spotlight",
    description: "Dark testimonial card with a mouse-tracking radial glow.",
    type: "registry:component",
    files: [{
      path: "src/registry/testimonial-spotlight/testimonial-spotlight.tsx",
      type: "registry:component",
    }],
  },
  "number-counter": {
    name: "number-counter",
    description: "Animated number that counts up to a target when it enters the viewport.",
    type: "registry:component",
    files: [{
      path: "src/registry/number-counter/number-counter.tsx",
      type: "registry:component",
    }],
  },
  "progress-ring": {
    name: "progress-ring",
    description: "SVG circular progress indicator with animated fill.",
    type: "registry:component",
    files: [{
      path: "src/registry/progress-ring/progress-ring.tsx",
      type: "registry:component",
    }],
  },
  "gradient-border-card": {
    name: "gradient-border-card",
    description: "Card with an animated rotating gradient border.",
    type: "registry:component",
    files: [{
      path: "src/registry/gradient-border-card/gradient-border-card.tsx",
      type: "registry:component",
    }],
  },
  "typewriter-effect": {
    name: "typewriter-effect",
    description: "Animated typewriter that types and deletes a list of words.",
    type: "registry:component",
    files: [{
      path: "src/registry/typewriter-effect/typewriter-effect.tsx",
      type: "registry:component",
    }],
  },
  "magnetic-button": {
    name: "magnetic-button",
    description: "Button that magnetically follows the cursor on hover.",
    type: "registry:component",
    files: [{
      path: "src/registry/magnetic-button/magnetic-button.tsx",
      type: "registry:component",
    }],
  },
  "avatar-group": {
    name: "avatar-group",
    description: "Overlapping avatar stack with gradient initials and overflow count.",
    type: "registry:component",
    files: [{
      path: "src/registry/avatar-group/avatar-group.tsx",
      type: "registry:component",
    }],
  },
  "stat-card": {
    name: "stat-card",
    description: "Metric card with accent bar, trend indicator, and icon.",
    type: "registry:component",
    files: [{
      path: "src/registry/stat-card/stat-card.tsx",
      type: "registry:component",
    }],
  },
  "timeline": {
    name: "timeline",
    description: "Vertical timeline with done/active/pending step states.",
    type: "registry:component",
    files: [{
      path: "src/registry/timeline/timeline.tsx",
      type: "registry:component",
    }],
  },
  "pricing-card": {
    name: "pricing-card",
    description: "Pricing card with highlighted plan, badge, and animated border.",
    type: "registry:component",
    files: [{
      path: "src/registry/pricing-card/pricing-card.tsx",
      type: "registry:component",
    }],
  },
  "step-progress": {
    name: "step-progress",
    description: "Multi-step progress in numbered, bars, and dots variants.",
    type: "registry:component",
    files: [{
      path: "src/registry/step-progress/step-progress.tsx",
      type: "registry:component",
    }],
  },
  "badge-collection": {
    name: "badge-collection",
    description: "Badge set with success, warning, error, info, outline and gradient variants.",
    type: "registry:component",
    files: [{
      path: "src/registry/badge-collection/badge-collection.tsx",
      type: "registry:component",
    }],
  },
  "skeleton-loader": {
    name: "skeleton-loader",
    description: "Animated skeleton placeholders for cards, text and circles.",
    type: "registry:component",
    files: [{
      path: "src/registry/skeleton-loader/skeleton-loader.tsx",
      type: "registry:component",
    }],
  },
  "feature-card": {
    name: "feature-card",
    description: "Feature card with icon bubble and hover shimmer.",
    type: "registry:component",
    files: [{
      path: "src/registry/feature-card/feature-card.tsx",
      type: "registry:component",
    }],
  },
  "code-snippet": {
    name: "code-snippet",
    description: "Dark code block with macOS chrome, language tag, and copy button.",
    type: "registry:component",
    files: [{
      path: "src/registry/code-snippet/code-snippet.tsx",
      type: "registry:component",
    }],
  },
  "particle-cursor": {
    name: "particle-cursor",
    description: "Canvas particle trail that follows the mouse cursor.",
    type: "registry:component",
    files: [{
      path: "src/registry/particle-cursor/particle-cursor.tsx",
      type: "registry:component",
    }],
  },
  "tilt-card": {
    name: "tilt-card",
    description: "3D perspective tilt card with glare highlight on hover.",
    type: "registry:component",
    files: [{
      path: "src/registry/tilt-card/tilt-card.tsx",
      type: "registry:component",
    }],
  },
  "animated-tabs": {
    name: "animated-tabs",
    description: "Tabs with pill, underline, and card style variants.",
    type: "registry:component",
    files: [{
      path: "src/registry/animated-tabs/animated-tabs.tsx",
      type: "registry:component",
    }],
  },
  "accordion": {
    name: "accordion",
    description: "Animated accordion with smooth height transitions.",
    type: "registry:component",
    files: [{
      path: "src/registry/accordion/accordion.tsx",
      type: "registry:component",
    }],
  },
  "github-contributions": {
    name: "github-contributions",
    description: "GitHub-style contribution heatmap grid.",
    type: "registry:component",
    files: [{
      path: "src/registry/github-contributions/github-contributions.tsx",
      type: "registry:component",
    }],
  },
  "github-stars": {
    name: "github-stars",
    description: "Star badge that fetches live star count from the GitHub API.",
    type: "registry:component",
    files: [{
      path: "src/registry/github-stars/github-stars.tsx",
      type: "registry:component",
    }],
  },
  "middle-truncation": {
    name: "middle-truncation",
    description: "Truncates long strings from the middle, preserving start and end.",
    type: "registry:component",
    files: [{
      path: "src/registry/middle-truncation/middle-truncation.tsx",
      type: "registry:component",
    }],
  },
  "theme-toggle-effect": {
    name: "theme-toggle-effect",
    description: "Animated sun/moon toggle button for dark/light mode.",
    type: "registry:component",
    files: [{
      path: "src/registry/theme-toggle-effect/theme-toggle-effect.tsx",
      type: "registry:component",
    }],
  },
  "icon-swap": {
    name: "icon-swap",
    description: "Button that swaps between two icons with flip, slide or fade animation.",
    type: "registry:component",
    files: [{
      path: "src/registry/icon-swap/icon-swap.tsx",
      type: "registry:component",
    }],
  },
  "apple-hello-effect-vi-demo": {
    name: "apple-hello-effect-vi-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-vi-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/apple-hello-effect-vi-demo.tsx")),
  },
  "apple-hello-effect-en-demo": {
    name: "apple-hello-effect-en-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-en-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/apple-hello-effect-en-demo.tsx")),
  },
  "theme-switcher-demo": {
    name: "theme-switcher-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-switcher-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/theme-switcher-demo.tsx")),
  },
  "wheel-picker-demo": {
    name: "wheel-picker-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-demo.tsx")),
  },
  "wheel-picker-form-demo": {
    name: "wheel-picker-form-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-form-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-form-demo.tsx")),
  },
  "work-experience-demo": {
    name: "work-experience-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/work-experience-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/work-experience-demo.tsx")),
  },
  "glowing-orb-demo": {
    name: "glowing-orb-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/glowing-orb-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/glowing-orb-demo.tsx")),
  },
  "morphing-text-demo": {
    name: "morphing-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/morphing-text-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/morphing-text-demo.tsx")),
  },
  "spotlight-card-demo": {
    name: "spotlight-card-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/spotlight-card-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/spotlight-card-demo.tsx")),
  },
  "neon-clock-demo": {
    name: "neon-clock-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/neon-clock-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/neon-clock-demo.tsx")),
  },
}